### ISSUE TITLE
Convert Recipes from Ollama to Replicate

### ISSUE THREAD

**Issue by deanwampler** [ibm-granite-community/granite-code-cookbook#123]
Convert the `Text_to_Shell*` and `Text_to_SQL` notebooks to use Replicate instead of Ollama.

These notebooks default to the `3b` model, which doesn't work that well often, while `20b` tends to work well, especially when on a Mac. Convert these notebooks to use Replicate instead of running locally.

**Comment by fayvor** [comment]
Yes. I can take this.

**Comment by fayvor** [comment]
Text_to_Shell [PR up here](https://github.com/ibm-granite-community/granite-code-cookbook/pull/128).

**Comment by fayvor** [comment]
Text_to_Shell_Exec [PR up here](https://github.com/ibm-granite-community/granite-code-cookbook/pull/130).

Text_to_SQL was already Replicate, so this completes the work.
