### ISSUE TITLE
`Coding_Assistant_in_VSCode` fixes needed

### ISSUE THREAD

**Issue by deanwampler** [ibm-granite-community/granite-code-cookbook#51]
`recipes/Coding_Assistant_in_VSCode/Coding_Assistant_in_VSCode.ipynb` needs a few fixes.

1. It should install 8b as well as 20b.
2. In the cell **Configure Continue to connect to a model on Replicate**, the example JSON mixes 8b and 20b logic.
3. Add the correct logic for the latest versions for both 8b and 20b.

**Comment by fayvor** [comment]
I'll take this issue. Should it be in the PM project?

**Comment by fayvor** [comment]
> Add the correct logic for the latest versions for both 8b and 20b.

The latest versions are hosted under the same identifiers as the previous versions:
https://ollama.com/library/granite-code

**Comment by fayvor** [comment]
[PR here.](https://github.com/ibm-granite-community/granite-code-cookbook/pull/57)

**Comment by deanwampler** [comment]
Fixed.
