### ISSUE TITLE
CLDK recipes - Don't regenerate the analysis every time?

### ISSUE THREAD

**Issue by deanwampler** [ibm-granite-community/granite-code-cookbook#63]
I suspect the `analysis.json` that is generated is the same every notebook. We currently delete it, since apparently the API won't run the analysis if it finds a file already. Is this actually okay? Is the file going to be the same every time?

The cost of redoing it every time is trivial, but we also want to make sure people understand the _intent_ of the API and how it gets used. When is it best to make sure you clean the old analysis vs. when it's fine to just keep the old one?

(NOTE: this shouldn't be changed this week, September 2nd...)

**Comment by rangeetpan** [comment]
Technically, if analysis.json is created once, it would read from that the second time and would not generate it.

**Comment by deanwampler** [comment]
That's what I thought. I assumed it would be the same, since the example library is the same.

What I would suggest is two changes:
1. Remove the cell that deletes the file.
2. Add comments to all the notebooks that analysis and this file will be the same no matter which notebook is run first, so sometimes the cells won't do anything.

**Comment by deanwampler** [comment]
Fixed
