### ISSUE TITLE
HAP recipe needs to use correct model name in comments

### ISSUE THREAD

**Issue by BishwaBhatta** [ibm-granite-community/granite-code-cookbook#77]
The HAP models in huggingface are called granite-guardian-hap-38m and granite-guardian-hap-125m.  The comments in the cookbook (hap.ipynb) refer to it as granite.38m.en.guardrail.  This needs to be updated

**Comment by adampingel** [comment]
Will assign to `ian-cho` after the invite is accepted.

**Comment by adampingel** [comment]
https://github.com/ibm-granite-community/granite-code-cookbook/pull/92
