### ISSUE TITLE
Move ollama setup to utils

### ISSUE THREAD

**Issue by rawkintrevo** [ibm-granite-community/granite-code-cookbook#80]

**Comment by rawkintrevo** [comment]
@adampingel upon reflection, I think it would be better to move ollama setup to a step in the workflow. Your thoughts?

**Comment by adampingel** [comment]
Sounds good to me.  We just want to make sure that this all easily discoverable for anyone down the road who is trying to reproduce the setup.  A few sentences in the wiki and a link could accomplish that.
